import type { Recipe } from './recipes.types'

export const seededRecipes: Recipe[] = [
  {
    id: 'sup-ayam-halia',
    title: 'Sup Ayam Halia',
    summary: 'Sup hangat dengan halia dan lada hitam untuk bantu badan rasa selesa dan bertenaga.',
    category: 'Soup',
    benefit: 'Warming',
    week: 'Week 1',
    prepTime: '35 minit',
    servings: '2 orang',
    heroColor: 'amber',
    ingredients: ['300g ayam tanpa kulit', '2 inci halia, dihiris nipis', '3 ulas bawang putih', '1 batang lobak merah', '700ml air', 'Sedikit lada hitam dan garam'],
    steps: ['Tumis bawang putih dan halia sehingga naik bau.', 'Masukkan ayam dan gaul hingga berubah warna.', 'Tuang air, kemudian masukkan lobak merah.', 'Reneh 20 minit sehingga ayam lembut.', 'Perasakan dengan lada hitam dan garam sebelum dihidang.'],
    pantryTips: ['Tambah sedikit daun sup jika ibu sudah selesa dengan herba.'],
    tags: ['berkuah', 'halia', 'ayam'],
    featured: true,
  },
  {
    id: 'bubur-nasi-pantang',
    title: 'Bubur Nasi Pantang',
    summary: 'Bubur lembut dengan ayam cincang, sesuai untuk hari yang perlukan hidangan ringan.',
    category: 'Comfort',
    benefit: 'Easy to digest',
    week: 'Week 1',
    prepTime: '30 minit',
    servings: '2 mangkuk',
    heroColor: 'rose',
    ingredients: ['1/2 cawan beras', '120g ayam cincang', '1 inci halia, ditumbuk', '1 sudu kecil minyak bijan', '700ml stok ayam', 'Sedikit garam'],
    steps: ['Basuh beras dan rebus bersama stok ayam sehingga kembang.', 'Masukkan halia dan ayam cincang.', 'Kacau selalu supaya bubur tidak berkerak.', 'Tambahkan minyak bijan dan garam bila bubur sudah pekat lembut.'],
    pantryTips: ['Simpan stok ayam siap rebus dalam peti sejuk untuk masak lebih cepat.'],
    tags: ['bubur', 'lembut', 'sarapan'],
    featured: true,
  },
  {
    id: 'ikan-singgang-kunyit',
    title: 'Ikan Singgang Kunyit',
    summary: 'Pilihan lauk ringan dengan kunyit dan asam gelugur yang menyegarkan.',
    category: 'Seafood',
    benefit: 'Light',
    week: 'Week 2',
    prepTime: '25 minit',
    servings: '2 orang',
    heroColor: 'sky',
    ingredients: ['2 keping ikan tenggiri', '1 inci kunyit hidup', '1 inci halia', '1 keping asam gelugur', '600ml air', 'Garam secukup rasa'],
    steps: ['Tumbuk kunyit dan halia sehingga lumat.', 'Didihkan air bersama bahan tumbuk dan asam gelugur.', 'Masukkan ikan dan masak sehingga isi ikan masak sepenuhnya.', 'Perasakan dengan sedikit garam dan hidang panas.'],
    pantryTips: ['Boleh ganti dengan isi ikan merah jika suka rasa yang lebih manis.'],
    tags: ['ikan', 'kunyit', 'lauk'],
    featured: false,
  },
  {
    id: 'teh-kurma-halia',
    title: 'Teh Kurma Halia',
    summary: 'Minuman ringkas yang hangat dengan rasa manis semula jadi daripada kurma.',
    category: 'Herbal',
    benefit: 'Milk support',
    week: 'Week 2',
    prepTime: '15 minit',
    servings: '2 cawan',
    heroColor: 'orange',
    ingredients: ['4 biji kurma tanpa biji', '1 inci halia', '500ml air', '1 sudu kecil madu jika perlu'],
    steps: ['Rebus air bersama halia yang dihiris dan kurma.', 'Biarkan mendidih perlahan selama 10 minit.', 'Tekan sedikit kurma supaya rasa lebih keluar.', 'Tapis dan tambah madu jika mahu.'],
    pantryTips: ['Sedap diminum waktu pagi atau selepas menyusu.'],
    tags: ['minuman', 'kurma', 'susu'],
    featured: true,
  },
  {
    id: 'ayam-kukus-serai',
    title: 'Ayam Kukus Serai',
    summary: 'Ayam kukus beraroma serai, sesuai bila mahu lauk tanpa berminyak.',
    category: 'Protein',
    benefit: 'Light',
    week: 'Week 2',
    prepTime: '40 minit',
    servings: '3 orang',
    heroColor: 'emerald',
    ingredients: ['350g ayam', '2 batang serai dititik', '1 inci halia', '2 ulas bawang putih', '1 sudu kecil minyak bijan', 'Sedikit garam'],
    steps: ['Gaulkan ayam dengan halia, bawang putih, garam dan minyak bijan.', 'Susun serai di bawah ayam.', 'Kukus 25 hingga 30 minit sehingga ayam masak.', 'Sudu sedikit kuah kukusan ke atas ayam sebelum hidang.'],
    pantryTips: ['Padankan dengan nasi panas atau bubur kosong.'],
    tags: ['kukus', 'ayam', 'protein'],
    featured: false,
  },
  {
    id: 'sup-sayur-labu',
    title: 'Sup Sayur Labu',
    summary: 'Sup labu lembut dengan rasa manis semula jadi, menenangkan perut.',
    category: 'Soup',
    benefit: 'Easy to digest',
    week: 'Week 1',
    prepTime: '20 minit',
    servings: '2 orang',
    heroColor: 'amber',
    ingredients: ['2 cawan labu dipotong dadu', '1 biji kentang kecil', '1 ulas bawang putih', '500ml air', '1 sudu kecil minyak zaitun', 'Sedikit garam'],
    steps: ['Tumis bawang putih dengan minyak zaitun.', 'Masukkan labu, kentang dan air.', 'Reneh hingga sayur lembut.', 'Lenyek sedikit supaya kuah lebih berkrim dan perasakan.'],
    pantryTips: ['Boleh blend halus jika ibu suka tekstur sup yang lebih lembut.'],
    tags: ['labu', 'sup', 'sayur'],
    featured: false,
  },
  {
    id: 'nasi-halia-ikan-bilis',
    title: 'Nasi Halia Ikan Bilis',
    summary: 'Nasi ringkas beraroma halia untuk pasangan lauk berkuah atau ayam kukus.',
    category: 'Comfort',
    benefit: 'Energy boosting',
    week: 'Week 3+',
    prepTime: '25 minit',
    servings: '3 orang',
    heroColor: 'orange',
    ingredients: ['2 cawan beras', '1 inci halia dihiris halus', '1 sudu besar ikan bilis kisar', '2 1/4 cawan air', '1 sudu kecil minyak sapi'],
    steps: ['Basuh beras dan toskan.', 'Gaul beras dengan halia, ikan bilis kisar dan minyak sapi.', 'Masukkan air dan masak seperti biasa sehingga nasi tanak.'],
    pantryTips: ['Sesuai dijadikan base meal untuk stok 2 hari.'],
    tags: ['nasi', 'halia', 'staple'],
    featured: false,
  },
  {
    id: 'omelet-daun-kucai',
    title: 'Omelet Daun Kucai',
    summary: 'Telur dadar lembut dengan daun kucai untuk menu cepat dan berkhasiat.',
    category: 'Protein',
    benefit: 'Energy boosting',
    week: 'Week 2',
    prepTime: '12 minit',
    servings: '2 orang',
    heroColor: 'violet',
    ingredients: ['3 biji telur', '1/4 cawan daun kucai dihiris', '1 sudu besar susu', 'Sedikit lada putih', '1 sudu kecil minyak'],
    steps: ['Pukul telur bersama susu dan lada putih.', 'Masukkan daun kucai.', 'Masak atas kuali kecil dengan api perlahan hingga lembut.'],
    pantryTips: ['Boleh lipat dengan isi ayam cincang jika mahu lebih mengenyangkan.'],
    tags: ['telur', 'cepat', 'protein'],
    featured: false,
  },
  {
    id: 'sup-kacang-merah-kurma',
    title: 'Sup Kacang Merah Kurma',
    summary: 'Sup manis ringan untuk snek petang yang mengenyangkan dan menyegarkan.',
    category: 'Snack',
    benefit: 'Energy boosting',
    week: 'Week 3+',
    prepTime: '45 minit',
    servings: '3 mangkuk',
    heroColor: 'rose',
    ingredients: ['1 cawan kacang merah rebus', '4 biji kurma', '800ml air', '2 hiris halia tua', 'Sedikit gula melaka jika perlu'],
    steps: ['Satukan semua bahan dalam periuk.', 'Reneh 15 hingga 20 minit sehingga rasa sebati.', 'Laraskan kemanisan sebelum dihidang.'],
    pantryTips: ['Simpan dalam peti sejuk untuk snek sejuk pada waktu siang.'],
    tags: ['snek', 'kacang merah', 'kurma'],
    featured: false,
  },
  {
    id: 'salmon-bakar-kunyit',
    title: 'Salmon Bakar Kunyit',
    summary: 'Ikan salmon dengan kunyit dan limau untuk hidangan moden yang tetap mesra pantang.',
    category: 'Seafood',
    benefit: 'Milk support',
    week: 'Week 3+',
    prepTime: '22 minit',
    servings: '2 orang',
    heroColor: 'sky',
    ingredients: ['2 ketul salmon', '1 sudu kecil kunyit serbuk', '1/2 biji limau nipis', '1 sudu kecil minyak zaitun', 'Sedikit garam'],
    steps: ['Gaul salmon dengan kunyit, minyak zaitun dan garam.', 'Bakar atau air-fry 10 hingga 12 minit.', 'Perah sedikit limau sebelum dihidang.'],
    pantryTips: ['Padankan dengan sayur kukus dan nasi halia.'],
    tags: ['salmon', 'omega', 'bakar'],
    featured: true,
  },
  {
    id: 'air-jintan-manis',
    title: 'Air Jintan Manis Suam',
    summary: 'Minuman suam yang ringan selepas makan dan sesuai dijadikan rutin harian.',
    category: 'Herbal',
    benefit: 'Easy to digest',
    week: 'Week 1',
    prepTime: '10 minit',
    servings: '2 cawan',
    heroColor: 'emerald',
    ingredients: ['1 sudu kecil jintan manis', '500ml air'],
    steps: ['Didihkan air bersama jintan manis selama 5 minit.', 'Biarkan suam dan tapis sebelum diminum.'],
    pantryTips: ['Boleh disediakan dalam termos kecil untuk minum sedikit demi sedikit.'],
    tags: ['minuman', 'jintan', 'penghadaman'],
    featured: false,
  },
  {
    id: 'roti-bakar-avokado-telur',
    title: 'Roti Bakar Avokado Telur',
    summary: 'Sarapan ringkas untuk minggu ketiga ke atas bila selera sudah semakin baik.',
    category: 'Snack',
    benefit: 'Energy boosting',
    week: 'Week 3+',
    prepTime: '15 minit',
    servings: '1 orang',
    heroColor: 'violet',
    ingredients: ['2 keping roti penuh gandum', '1/2 biji avokado', '1 biji telur rebus', 'Sedikit lada hitam'],
    steps: ['Bakar roti hingga garing sedikit.', 'Lenyek avokado di atas roti.', 'Susun hirisan telur rebus dan tabur lada hitam.'],
    pantryTips: ['Cepat disediakan bila ibu perlukan sarapan padat tenaga.'],
    tags: ['sarapan', 'avokado', 'telur'],
    featured: false,
  },
  {
    id: 'sup-daging-lobak-putih',
    title: 'Sup Daging Lobak Putih',
    summary: 'Sup daging berempah lembut yang sesuai untuk hari ibu perlukan hidangan lebih mengenyangkan.',
    category: 'Soup',
    benefit: 'Energy boosting',
    week: 'Week 3+',
    prepTime: '50 minit',
    servings: '3 orang',
    heroColor: 'amber',
    ingredients: ['250g daging batang pinang', '1 batang lobak putih', '2 inci halia', '2 ulas bawang putih', '900ml air', 'Sedikit lada hitam'],
    steps: ['Tumis halia dan bawang putih sehingga naik bau.', 'Masukkan daging dan gaul hingga permukaan berubah warna.', 'Tuang air dan reneh 25 minit.', 'Masukkan lobak putih dan teruskan mereneh sehingga lembut.', 'Perasakan dengan lada hitam sebelum dihidang.'],
    pantryTips: ['Boleh masak sekali banyak dan panaskan semula untuk makan malam.'],
    tags: ['daging', 'sup', 'mengenyangkan'],
    featured: false,
  },
  {
    id: 'ikan-merah-kukus-halia',
    title: 'Ikan Merah Kukus Halia',
    summary: 'Ikan kukus dengan halia, minyak bijan, dan daun bawang untuk lauk cepat yang lembut.',
    category: 'Seafood',
    benefit: 'Light',
    week: 'Week 2',
    prepTime: '18 minit',
    servings: '2 orang',
    heroColor: 'sky',
    ingredients: ['2 ketul ikan merah', '1 1/2 inci halia', '1 sudu kecil minyak bijan', '1 batang daun bawang', 'Sedikit garam'],
    steps: ['Susun halia di atas ikan merah.', 'Renjis minyak bijan dan sedikit garam.', 'Kukus 10 hingga 12 minit sehingga ikan masak.', 'Tabur daun bawang sebelum hidang.'],
    pantryTips: ['Padankan dengan bubur atau nasi halia untuk makan tengah hari ringan.'],
    tags: ['ikan merah', 'kukus', 'halia'],
    featured: false,
  },
  {
    id: 'bubur-oat-kurma-epal',
    title: 'Bubur Oat Kurma Epal',
    summary: 'Sarapan lembut yang cepat disediakan bila ibu perlukan pilihan manis semula jadi.',
    category: 'Comfort',
    benefit: 'Easy to digest',
    week: 'Week 1',
    prepTime: '10 minit',
    servings: '1 mangkuk besar',
    heroColor: 'rose',
    ingredients: ['1/2 cawan oat', '2 biji kurma cincang', '1/2 biji epal dipotong kecil', '250ml susu oat atau air', 'Sedikit serbuk kayu manis'],
    steps: ['Masukkan oat, susu oat, kurma, dan epal ke dalam periuk kecil.', 'Masak atas api perlahan sambil dikacau sehingga pekat.', 'Tabur sedikit serbuk kayu manis sebelum dihidang.'],
    pantryTips: ['Boleh sediakan versi overnight oat untuk pagi yang sibuk.'],
    tags: ['oat', 'sarapan', 'kurma'],
    featured: false,
  },
  {
    id: 'ayam-panggang-kurma-bawang',
    title: 'Ayam Panggang Kurma Bawang',
    summary: 'Ayam panggang lembut dengan rasa manis bawang dan kurma, sesuai untuk minggu kedua dan seterusnya.',
    category: 'Protein',
    benefit: 'Milk support',
    week: 'Week 2',
    prepTime: '35 minit',
    servings: '3 orang',
    heroColor: 'orange',
    ingredients: ['350g isi ayam', '3 biji kurma tanpa biji', '1/2 biji bawang holland', '1 inci halia', '1 sudu kecil minyak zaitun', 'Sedikit garam'],
    steps: ['Kisar kurma, bawang, halia, minyak zaitun, dan garam menjadi pes ringkas.', 'Gaul pes dengan ayam dan perap 10 minit.', 'Panggang atau air-fry sehingga ayam masak dan keperangan ringan.'],
    pantryTips: ['Sedap dimakan bersama sup sayur atau salad timun suam.'],
    tags: ['ayam', 'kurma', 'panggang'],
    featured: true,
  },
  {
    id: 'puding-sagu-halia',
    title: 'Puding Sagu Halia',
    summary: 'Pencuci mulut ringan dengan sentuhan halia untuk variasi snek petang yang mesra pantang.',
    category: 'Snack',
    benefit: 'Light',
    week: 'Week 3+',
    prepTime: '20 minit',
    servings: '4 cawan kecil',
    heroColor: 'emerald',
    ingredients: ['1/2 cawan sagu kecil', '600ml air', '1 inci halia diketuk', '150ml santan cair', 'Sedikit gula melaka'],
    steps: ['Rebus sagu bersama air dan halia sehingga jernih.', 'Toskan dan bilas sebentar.', 'Panaskan santan cair dengan sedikit gula melaka.', 'Tuang ke atas sagu ketika hendak dihidang.'],
    pantryTips: ['Sedap dimakan suam atau sejuk, bergantung pada selera ibu.'],
    tags: ['sagu', 'puding', 'snek'],
    featured: false,
  },
  {
    id: 'sup-tofu-sawi-halia',
    title: 'Sup Tofu Sawi Halia',
    summary: 'Sup vegetarian lembut dengan tofu dan sawi untuk hari yang perlukan rasa lebih ringan.',
    category: 'Soup',
    benefit: 'Easy to digest',
    week: 'Week 1',
    prepTime: '18 minit',
    servings: '2 orang',
    heroColor: 'violet',
    ingredients: ['1 ketul tofu lembut', '1 genggam sawi', '1 inci halia', '600ml air', '1 sudu kecil minyak bijan', 'Sedikit garam'],
    steps: ['Didihkan air bersama halia.', 'Masukkan tofu dan reneh 5 minit.', 'Masukkan sawi dan minyak bijan.', 'Perasakan ringan sebelum dihidang.'],
    pantryTips: ['Tambah cendawan shimeji jika mahu tekstur tambahan.'],
    tags: ['tofu', 'sawi', 'sup'],
    featured: false,
  },
]
